[package]
name = "snowflake-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
termion = "4.0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
iced-x86 = { version = "1.21.0", features = ["code_asm"] }